---
deployment:
  tasks:
    - set -e
    - export DEPLOYPATH=/home2/leylasaf/public_html
    - export APPPATH=/home2/leylasaf/leysafaris/leysafaris
    - export REPO_ROOT=$PWD
    - /bin/bash scripts/deploy-production.sh
